### ISSUE TITLE
No clear documentation on usage of beta version in actual ember addons

### ISSUE THREAD

**Issue by robinborst95** [ember-cli-code-coverage/ember-cli-code-coverage#347]
~Unlike the in-repo addons we have in our main repository, we also have actual addons with files in `addon` and `app`. When using the beta version, all `app` files are still covered, but the `addon` files aren't anymore. I've tried to resolve this with `modifyAssetLocation` (we don't need the `--path` option in the actual addons), but all `relativePath`s contained `dummy` (corresponding to `app`). So, it seems like the coverage is not only not reported, it's also not calculated at all anymore.~

~I was quite surprised that this wasn't covered by the tests, as I do see `my-addon` in the `test-packages`. However, that repo isn't used in any test, and I couldn't get a simple test working, so I guess that would need some more investigation.~

The Readme does mention how to setup instrumentation in in-repo addons, but it doesn't mention that this same setup also applies to actual/standalone addons. In such addons that have `app` files (like our addon does) there is no setup example as well . It can be inferred from the other examples, but having it mentioned explicitly definitely helps with the setup.

**Comment by rwjblue** [comment]
Hmm, there really isn't a significant difference between in-repo addons and external/standalone addons from our perspective. Did you confirm that the external ones are doing the same setup (in order to get instrumentation)?

```js
module.exports = {
  name: require('./package').name,

  options: {
    babel: {
      plugins: [...require('ember-cli-code-coverage').buildBabelPlugin()],
    },
  },
};
```

**Comment by robinborst95** [comment]
Ah, I see where the confusion comes from. The setup for standalone addons isn't covered in the Readme (it only says this setup is for in-repo addons), so let's make sure to update this by saying it's both for in-repo addons and standalone addons :+1: 

The setup we tried was actually something that wasn't documented either, but it led to reported coverage of the `app` files in our addon, using this:
```js
let app = new EmberAddon(defaults, {
  babel: {
    plugins: [...require('ember-cli-code-coverage').buildBabelPlugin()]
  },
});
```

As both of these aren't covered in the Readme, I'll update this issue to say that it's actually not documented that clearly.

**Comment by rogeraraujo90** [comment]
> Ah, I see where the confusion comes from. The setup for standalone addons isn't covered in the Readme (it only says this setup is for in-repo addons), so let's make sure to update this by saying it's both for in-repo addons and standalone addons 👍
> 
> The setup we tried was actually something that wasn't documented either, but it led to reported coverage of the `app` files in our addon, using this:
> 
> ```js
> let app = new EmberAddon(defaults, {
>   babel: {
>     plugins: [...require('ember-cli-code-coverage').buildBabelPlugin()]
>   },
> });
> ```
> 
> As both of these aren't covered in the Readme, I'll update this issue to say that it's actually not documented that clearly.
> 
> After doing the setup properly, it still didn't work for us though, but that has to do with the name of our addon and has been reported [here](https://github.com/kategengler/ember-cli-code-coverage/issues/340) already.

Hey, not sure if this wasn't released yet because of this but using this configuration is leading the Coverage from the main app be impacted by the addon coverage.

I've tried exclude `node_modules` by adding it in the `config/coverage.js` file but doesn't work.

![image](https://user-images.githubusercontent.com/6045678/218490355-08a19270-41fa-49bd-8640-ca6e32f88e19.png)

**Comment by anehx** [comment]
> Hmm, there really isn't a significant difference between in-repo addons and external/standalone addons from our perspective. Did you confirm that the external ones are doing the same setup (in order to get instrumentation)?
> 
> ```js
> module.exports = {
>   name: require('./package').name,
> 
>   options: {
>     babel: {
>       plugins: [...require('ember-cli-code-coverage').buildBabelPlugin()],
>     },
>   },
> };
> ```

I just did this in an addon I'm maintaining and it works. However, this makes `ember-cli-code-coverage` a dependency of the addon using it when it should only be used for testing the addon. How can we fix this?

**Comment by vstefanovic97** [comment]
@rogeraraujo90 You can fix your problem by doing this inside your addons `index.js`

```
// Instrument addon code with istanbul only when it's built from that addons test app
  init(parent) {
    this._super.init.apply(this, arguments);

    const parentName =
      typeof parent.name === 'function' ? parent.name() : parent.name;

    if (parentName === require('./package').name) {
      this.options = {
        ...this.options,
        babel: {
          plugins: [
            ...(this.options.babel.plugins || []),
            ...require('ember-cli-code-coverage').buildBabelPlugin(),
          ],
        },
      };
    }
  },
```
This way we make sure the babel plugin is included only during the build of the addon itself, and not when your host application is building the addon
