### ISSUE TITLE
require.buildBabelPlugin is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by GradedJestRisk** [ember-cli-code-coverage/ember-cli-code-coverage#348]
## Problem
When running coverage with latest no-beta version (1.0.3), task fails with error message
`require.buildBabelPlugin is not a function or its return value is not iterable`

See [this repo](https://github.com/GradedJestRisk/ember-with-coverage) to reproduce the problem on a fresh-generated application
``` shell
ember new ember-with-coverage
ember install ember-cli-code-coverage
```

### System
```js
ember-cli: 3.24.0
node: 14.17.6
os: linux x64
```

### Setup

```js
  let app = new EmberApp(defaults, {
    babel: {
      plugins: [...require('ember-cli-code-coverage').buildBabelPlugin()],
    },
  });
```

**Comment by notmessenger** [comment]
I tried every released version in my application (not a new clean install) and continued to receive the same error.

**Comment by jsolano** [comment]
1.0.3 version doesn't support buildBabelPlugin, change to Beta version or see documentation for 1.0.3

**Comment by notmessenger** [comment]
> 1.0.3 version doesn't support buildBabelPlugin, change to Beta version or see documentation for 1.0.3

Of course that makes sense! Followed the directions for `1.0.3` (not those in `master`) and works as expected.  Thanks!

**Comment by rwjblue** [comment]
Sorry @notmessenger. I'll try to review open issues for the beta and get it released as stable.

**Comment by IgnaceMaes** [comment]
I just ran into this issue again.

Wouldn't it make sense to have the documentation for version `1.0.3` on master, as that is the version which is installed when running `ember install ember-cli-code-coverage`?
