### ISSUE TITLE
Version 2.0.1 not published

### ISSUE THREAD

**Issue by ndekeister-us** [ember-cli-code-coverage/ember-cli-code-coverage#399]
Hello,

The version 2.0.1 was not published (see https://github.com/ember-cli-code-coverage/ember-cli-code-coverage/actions/runs/6784119305/job/18439775319) 

Any chance you could fix publish to npm?

**Comment by SergeAstapov** [comment]
@ndekeister-us this is known issue, tracked in https://github.com/ember-cli-code-coverage/ember-cli-code-coverage/issues/384#issuecomment-1798547101.

this duplicates #384
