### ISSUE TITLE
Coverage for gjs/gts files do not work for embroider apps

### ISSUE THREAD

**Issue by cah-brian-gantzler** [ember-cli-code-coverage/ember-cli-code-coverage#407]
Upgraded to 2.1.1, the gjs/gts files do not appear in the coverage output. 

This seems to be an issue with embroider. 

@vstefanovic97 was able to reproduce the issue. Please update any more information here.

**Comment by cah-brian-gantzler** [comment]
More questions that answers.

I only get test coverage when `-s` is added to the `ember t`. Without it, no coverage is written. 

Adding your method of 
```
const path = require('path');

module.exports = {
  modifyAssetLocation(root, relativePath) {
    if (relativePath.includes('/app-name/')) {
      return path.join('app', relativePath.split('/app-name/')[1]);
    }

    return false;
  },
};
```

Does seem to work. I get the gjs/gts files showing. But I dont know why because adding a `console.log(relativePath);` as the first statement shows that all the relative paths passed do not have the app name in them. 
```
components/invoice-master-listing.js
components/invoice-master-status.js
components/invoice-master-view.js
components/invoice-z120-export.js
components/invoice/admin/credit-review-item.js
components/invoice/admin/invoice-report.js
components/invoice/admin/open-cycles.js
components/invoice/admin/open-disputes-and-deferreds-item.js
components/invoice/admin/open-z120-invoice-review-item.js
components/invoice/administrator-invoice-edit.js
```

Which means the method should only be returning false all the time. However if I comment everything out and only return false all the time, it doesnt work. 

gjs/gts files  also seem to be correct on lines. All js/hbs versions are off by one line (have been for a long time for me)

**Comment by RobbieTheWagner** [comment]
Thanks for digging in @cah-brian-gantzler! @vstefanovic97 do you know what might be going on here?

**Comment by vstefanovic97** [comment]
@RobbieTheWagner it has something to do with how Embroider is copying over some files in some tmp dir, I didn't have time to fully investigate and come up with a proper solution due to work, but hope to get back to this soon

**Comment by bgantzler** [comment]
I see some people in discord where also reporting that coverage only works when -s is applied. 

On a brand new app, it appears to work without the -s. Not sure why. On my full app it does not. 

Brand new app with embroider though is missing coverage for gjs/gts still. Will try adding the modifyAsset code from above

**Comment by vstefanovic97** [comment]
@RobbieTheWagner, @cah-brian-gantzler I think I've identified several issues and fixes, working on adding better test cases for future.
Hope to push the fixes soon.
Btw @RobbieTheWagner are you maybe able to give me permissions just to run CI by myself so I don't need to ping you every time tests fail on CI?

**Comment by cah-brian-gantzler** [comment]
Great to hear. Looking forward to it. Appreciate your efforts.

**Comment by SergeAstapov** [comment]
@vstefanovic97 you won’t need to ask for that from now on as you already contributed to this repo so CI will kick off automatically

**Comment by vstefanovic97** [comment]
@cah-brian-gantzler, @RobbieTheWagner I just made a PR
https://github.com/ember-cli-code-coverage/ember-cli-code-coverage/pull/408
That I hope should resolve most of the issues.
It fixes:
* App with `throwUnlessParallelizable: true` (ember-cli-babel)
* Classic app with `ember-template-imports` (added tests for this)
* Embroider app with `ember-template-imports` (wasn't able to add test case but verified on my local)

**Comment by RobbieTheWagner** [comment]
Can we close this now?

**Comment by SergeAstapov** [comment]
@cah-brian-gantzler we would appreciate if you could confirm if you could try v2.1.2 and confirm if issues reported here resolved (except `ember s` scenario as it's separate)

**Comment by cah-brian-gantzler** [comment]
Will do that sometime today

**Comment by cah-brian-gantzler** [comment]
I have confirmed updating to 2.1.2 producing the expected results for gjs/gts when using `COVERAGE=true ember t -s`.

Also want to note that the lines marked in the HTML are the correct lines. In the .js files they are off by one line.

**Comment by cah-brian-gantzler** [comment]
I hadnt noticed before but its only components, all other (controllers, routes, etc) are on the correct lines. It seems only components are off by one line

![image](https://github.com/ember-cli-code-coverage/ember-cli-code-coverage/assets/1529286/dc2fc360-a49d-41bd-b2fc-8036be80a8bc)

**Comment by SergeAstapov** [comment]
@cah-brian-gantzler just to confirm, this 1 line off issue is present only for components in .js format and not present for .gts/.gjs?

**Comment by cah-brian-gantzler** [comment]
That is correct. only .js.     Here is a snippet from a gts file (you can see the `</template>` at the top.

Interesting, I am assuming that services (line 21) are not marked as accessed even though they are referenced (line 36). Makes sense, how would you know. Yet tracked variables (line 30) are. Are the 2 times (line 30) sets I wonder, since gets were at least 5 (line 37). Must be why the service isnt marked, Variables must be only marked as sets only.

![image](https://github.com/ember-cli-code-coverage/ember-cli-code-coverage/assets/1529286/cdc127ad-bc1e-4ce2-a8f3-ca7cfac84538)

**Comment by cah-brian-gantzler** [comment]
This issue, as is, can be closed. Will open another issue for the off by one.
