### ISSUE TITLE
Express vulnerable to XSS - Dependency on express 4.19.2.

### ISSUE THREAD

**Issue by janpospisil-eaton** [ember-cli-code-coverage/ember-cli-code-coverage#424]
Hi, our last cyber security scan resulted in a high risk being detected regarding the **expressjs/express** dependency that is used within this project. Can you update the reference and use latest version 4.21.0 ?

https://github.com/advisories/GHSA-qw6h-vgh9-j6wx

Thank you.

**Comment by SergeAstapov** [comment]
`ember-cli-code-coverage` declares dependency on `"express": "^4.17.3"`, hence your package manager can pull latest 4.x without need for `ember-cli-code-coverage` to do anything

**Comment by janpospisil-eaton** [comment]
The issue is being reported as a transitive dependency, which originates in **ember-cli-code-coverage**.  Any version of **express** below 4.20.0 is marked as vulnerable to the XSS attack.  Even if I create a direct dependency on latest **express** 4.x in the project, the **ember-cli-code-coverage** will still require older version with the vulnerability.

**Comment by SergeAstapov** [comment]
> the ember-cli-code-coverage will still require older version with the vulnerability.

nope it's not. it's up to you package manager to decide which version to pull, as `ember-cli-code-coverage` says "minimum 4.17.3"

**Comment by janpospisil-eaton** [comment]
Hi Serge,

I've added [a resolution](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to `package.json` to use the express 4.21.0 version and I can confirm that package manager correctly use it.

My suggestion still would be to increase the minimum dependency to "express": "^4.20.0" to resolve the XSS vulnerability.
Are there any compatibility issues with other dependencies ? Does it require broader re-factoring ?

Thank you,
Jan

**Comment by RobbieTheWagner** [comment]
I would think we could probably update the express dep?
